-- =========================================================================
-- MapMeet — a daily cap on how many events one account may pin
-- =========================================================================
-- Anyone signed in can drop a marker, and nothing stopped one account
-- from carpeting a city with them. The cap is per role:
--
--   user     →  5 markers / day
--   premium  → 25 markers / day
--   designer, support, admin, owner → unlimited
--
-- "All roles except premium are unlimited" holds because the only other
-- roles are staff, and staff_roles() is already THE list — a new staff
-- tier inherits unlimited automatically, with no edit here.
--
-- ⚠ To change the numbers, edit `daily_event_limit()` below and nothing
--   else. The client mirror lives in utils/roles.ts and must move with
--   it; the server is the authority either way.
--
-- THREE DECISIONS WORTH THE INK
--
-- 1. A ROLLING 24 HOURS, not a calendar day.
--    A calendar day needs a timezone, and there is no good answer for
--    which: the account's, the device's, or the server's. Whichever is
--    picked, the cap also resets at a wall-clock instant every account
--    can see coming, so five markers at 23:59 plus five at 00:01 is ten
--    markers in two minutes. A rolling window has no such edge and needs
--    no timezone at all.
--
-- 2. A LEDGER TABLE, not `count(*) from events`.
--    Events are hard-deleted. Counting live rows would mean "delete your
--    five, pin five more" resets the cap on demand — and since an insert
--    fans out to a group chat and (soon) push, the churn is worth more to
--    a spammer than the markers are. `event_creations` is append-only, so
--    a deleted event still spends its slot. It also survives as the only
--    record that the event ever existed.
--
-- 3. THE SERVER IS THE ENFORCER.
--    RLS lets a client INSERT into `events` directly, so a hand-rolled
--    request skips every check the app makes. The trigger is the cap; the
--    UI counter exists so people aren't surprised by it.
--
-- Imported events (source <> 'user') are exempt: they are inserted by the
-- ingest bots under service_role, and the cap is about people.
--
-- Idempotent: safe to re-run.
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. The numbers, in one place
-- -------------------------------------------------------------------------
/** Markers per rolling 24h for a given profiles.role. NULL = unlimited.
 *
 *  Written as a fall-through rather than a lookup per role so that an
 *  unrecognised or NULL role lands on the strictest tier. Failing open
 *  here would mean a missing profile row buys unlimited markers. */
create or replace function public.daily_event_limit(p_role text)
returns integer language sql stable as $$
  select case
    when p_role = any(public.staff_roles()) then null
    when p_role = 'premium'                 then 25
    else                                          5
  end;
$$;

-- -------------------------------------------------------------------------
-- 2. The ledger
-- -------------------------------------------------------------------------
-- One row per marker pinned, ever. Append-only: nothing in the app
-- updates or deletes from it, and the only cleanup is the cascade when
-- an account is deleted.
--
-- `event_id` deliberately carries NO foreign key. The row has to outlive
-- the event it records — that is the whole point of decision 2 — so it
-- is a plain uuid that may well point at something that no longer
-- exists. It is `unique` so the backfill below and the trigger can never
-- double-count the same event.
create table if not exists public.event_creations (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  event_id   uuid unique,
  created_at timestamptz not null default now()
);

-- The only query that runs against this table: "this account, last 24h".
create index if not exists event_creations_user_time_idx
  on public.event_creations (user_id, created_at desc);

alter table public.event_creations enable row level security;

-- No policies, on purpose. Reads go through my_event_quota() and writes
-- through the trigger, both SECURITY DEFINER; a client has no business
-- touching the table directly, and an account must not be able to erase
-- its own history to buy back slots.
revoke all on public.event_creations from anon, authenticated;

-- Seed the window that is already in flight, so the cap starts biting
-- immediately instead of handing everyone a fresh five.
insert into public.event_creations (user_id, event_id, created_at)
select e.creator_id, e.id, e.created_at
  from public.events e
 where e.source = 'user'
   and e.creator_id is not null
   and e.created_at > now() - interval '24 hours'
on conflict (event_id) do nothing;

-- -------------------------------------------------------------------------
-- 3. Enforcement
-- -------------------------------------------------------------------------
/** BEFORE INSERT on events. Counts the account's last 24h, refuses when
 *  it is at the cap, and otherwise records the marker.
 *
 *  Trigger order matters and is alphabetical for the same timing:
 *  enforce_can_post_events → events_enforce_daily_limit →
 *  events_enforce_pin_style. So a banned or muted account is turned away
 *  before it can spend a slot.
 *
 *  The advisory lock is what makes the count trustworthy. Without it two
 *  simultaneous inserts from the same account both read "4 used" and
 *  both pass. It is keyed on the creator, so it never serialises anything
 *  but one account racing itself, and being an xact lock it is released
 *  by COMMIT or ROLLBACK with no cleanup path to get wrong. */
create or replace function public.enforce_daily_event_limit()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_limit  integer;
  v_used   integer;
  v_oldest timestamptz;
begin
  -- Imported rows: not a person pinning a marker.
  if coalesce(new.source, 'user') <> 'user' or new.creator_id is null then
    return new;
  end if;

  select public.daily_event_limit(p.role) into v_limit
    from public.profiles p where p.id = new.creator_id;
  if not found then
    v_limit := public.daily_event_limit('user');
  end if;

  if v_limit is not null then
    perform pg_advisory_xact_lock(
      hashtext('mapmeet_event_quota'), hashtext(new.creator_id::text));

    select count(*)::int, min(c.created_at)
      into v_used, v_oldest
      from public.event_creations c
     where c.user_id = new.creator_id
       and c.created_at > now() - interval '24 hours';

    if v_used >= v_limit then
      -- Machine-readable on purpose: the client splits on spaces to show
      -- the cap and the exact minute the next slot opens. Same shape as
      -- ACCOUNT_MUTED_UNTIL. 42501 = insufficient_privilege.
      raise exception 'DAILY_EVENT_LIMIT % %',
        v_limit,
        to_char((v_oldest + interval '24 hours') at time zone 'UTC',
                'YYYY-MM-DD"T"HH24:MI:SS"Z"')
        using errcode = '42501';
    end if;
  end if;

  -- Logged for unlimited accounts too, so the ledger is a complete
  -- history and a role change can't leave a gap in it.
  insert into public.event_creations (user_id, event_id)
  values (new.creator_id, new.id)
  on conflict (event_id) do nothing;

  return new;
end;
$$;

drop trigger if exists events_enforce_daily_limit on public.events;
create trigger events_enforce_daily_limit
  before insert on public.events
  for each row execute function public.enforce_daily_event_limit();

-- -------------------------------------------------------------------------
-- 4. What the client asks before it opens the wizard
-- -------------------------------------------------------------------------
/** The viewer's own allowance. `max_per_day` NULL means unlimited, and
 *  `resets_at` is when the oldest marker in the window ages out — i.e.
 *  the first moment a slot frees up. Returns no rows when signed out. */
create or replace function public.my_event_quota()
returns table (used integer, max_per_day integer, resets_at timestamptz)
language plpgsql stable security definer set search_path = public as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then
    return;
  end if;

  select public.daily_event_limit(p.role) into max_per_day
    from public.profiles p where p.id = v_uid;
  if not found then
    max_per_day := public.daily_event_limit('user');
  end if;

  select count(*)::int, min(c.created_at) + interval '24 hours'
    into used, resets_at
    from public.event_creations c
   where c.user_id = v_uid
     and c.created_at > now() - interval '24 hours';

  return next;
end;
$$;

grant execute on function public.daily_event_limit(text) to authenticated;
grant execute on function public.my_event_quota()        to authenticated;
